<?php

namespace PirateBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobSubmissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobSubmissionRepository extends EntityRepository
{
}
