<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * job_submissionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class job_submissionRepository extends EntityRepository
{
}
